# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Untitled' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'untitled' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(1005, 873)
    @driver.find_element(:css, 'button').click
    @driver.find_element(:css, 'html').click
    @driver.find_element(:css, 'html').click
    @driver.find_element(:css, 'button').click
    @driver.find_element(:css, 'button').click
    element = @driver.find_element(:css, 'button')
    @driver.action.double_click(element).perform
    @driver.find_element(:css, 'button').click
    @driver.find_element(:css, 'button').click
    @driver.find_element(:css, 'button').click
    @driver.close
  end
end
